#!/usr/bin/env bash

input="$(cat)"

if command -v jq >/dev/null 2>&1; then
  fp="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"
else
  fp="$(printf '%s' "$input" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
fi

[ -n "$fp" ] || exit 0

# Match $HOME/.claude/settings.json and $HOME/.claude-*/settings.json only.
# settings.local.json has a different basename, so it is not matched.
case "$fp" in
  "$HOME"/.claude/settings.json|"$HOME"/.claude-*/settings.json) ;;
  *) exit 0 ;;
esac

# Don't catch the shared source itself (belt & braces; its files live under a
# different path and have different names anyway).
case "$fp" in
  "$HOME"/.claude-shared/*) exit 0 ;;
esac

cat >&2 <<EOF
Refusing to edit $fp directly — it is generated by the claude-shared sync
(User level: Managed > CLI > Local > Project > User). Managed keys are
overwritten on the next sync; route all changes through the dotfiles instead:
  • all accounts → ~/.claude-shared/settings/base.settings.json
  • this account → ~/.claude-shared/settings/overrides/<account>.settings.json
then run: ~/.claude-shared/sync.sh --apply
EOF
exit 2
