#!/usr/bin/env bash

input="$(cat)"

if command -v jq >/dev/null 2>&1; then
  fp="$(printf '%s' "$input" | jq -r '.tool_input.file_path // empty')"
else
  fp="$(printf '%s' "$input" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p')"
fi

[ -n "$fp" ] || exit 0

# Match $HOME/.claude/CLAUDE.md and $HOME/.claude-*/CLAUDE.md only.
case "$fp" in
  "$HOME"/.claude/CLAUDE.md|"$HOME"/.claude-*/CLAUDE.md) ;;
  *) exit 0 ;;
esac

# Don't catch the shared source itself (its file is base.CLAUDE.md, not
# CLAUDE.md, so the patterns above already exclude it — this is belt & braces).
case "$fp" in
  "$HOME"/.claude-shared/*) exit 0 ;;
esac

cat >&2 <<EOF
Refusing to edit $fp directly — it is generated by the claude-shared sync and
will be overwritten on the next run (User level: Managed > Project > User).

To change user-level memory, edit the dotfiles source instead:
  • all accounts → ~/.agents-shared/base.AGENTS.md
  • this account → ~/.claude-shared/claude-md/overrides/<account>.CLAUDE.md
then run: ~/.claude-shared/sync.sh --apply
EOF
exit 2
